feat: react typescript syntax error message
tscircuit/snippets pull request #218
Opened 2024-11-15 04:31 UTC by kom-senapati

Closes #215 

![image](https://github.com/user-attachments/assets/ca0e58da-f490-4b69-b82a-f499e20e932a)

I have added a util function and used it within the hook to return the react syntax error message.

2024-11-15 04:31 UTC, kom-senapati commented
/claim #215

2024-11-15 04:47 UTC, seveibar requested changes

2024-11-15 04:47 UTC, seveibar commented on src/hooks/use-run-tsx/index.tsx
> +    const error = getSyntaxError(code);
```suggestion
    const syntaxError = getSyntaxError(code);
```

2024-11-15 04:47 UTC, seveibar commented on src/hooks/use-run-tsx/index.tsx
> +    console.log("Syntax error: ", error)
```suggestion
```

2024-11-15 04:59 UTC, kom-senapati commented on src/hooks/use-run-tsx/index.tsx
> +    const error = getSyntaxError(code);
Ok

2024-11-15 04:59 UTC, kom-senapati commented on src/hooks/use-run-tsx/index.tsx
> +    console.log("Syntax error: ", error)
Aah forgot it

2024-11-15 05:52 UTC, seveibar commented
Can you make sure the tests pass and the format check passes, tyty

2024-11-15 06:21 UTC, kom-senapati commented
I don't I did code changes for tests to break, I think its some existing issue
Could you please check @seveibar

2024-11-15 06:44 UTC, seveibar approved these changes

2024-11-16 12:04 UTC, kom-senapati commented
Can you merge this @seveibar

2024-11-16 16:14 UTC, merged