fix: add manual_json validation and playwright-test
tscircuit/snippets pull request #269
Opened 2024-11-21 11:09 UTC by RohittCodes

refactored: manual_edit_json template ingestion into db.
included playwright tests

fixes: #261 
/claim #261

cc: @seveibar

2024-11-21 11:14 UTC, RohittCodes commented
forgot to claim this earlier
/claim #265

2024-11-22 05:45 UTC, RohittCodes commented
i forgot to claim the bounty for #265. and the fix for it temporarily solved the issue. i.e., whenever a new snippet was created it still showed the "Unsaved changes" text. This PR solves the issues with `manual_edit_json`.

2024-11-22 21:47 UTC, seveibar commented on fake-snippets-api/lib/db/db-client.ts
> +      manual_edits_json: JSON.stringify(manualEditsJsonTemplate, null, 2),
if there is an issue with the default value, that should be handled on the frontend the first time it's selected

2024-11-22 21:48 UTC, seveibar requested changes
you didn't test saving the manual edits file, you just set a default value on the server and showed it loads in both views.

you must hit run/save and ensure that edits to it are saved

2024-11-23 01:08 UTC, RohittCodes commented on fake-snippets-api/lib/db/db-client.ts
> +      manual_edits_json: JSON.stringify(manualEditsJsonTemplate, null, 2),
Uhh, sure..

2024-11-24 05:28 UTC, RohittCodes commented
@seveibar all the failing tests are passing in my local setup again. Not sure what's causing the checks fail here. 🤷‍♂️

2024-11-24 05:30 UTC, seveibar commented
@RohittCodes can you make sure youve got the latest deps by running "bun i" locally then rerunning tests. Is it a timeout issue on ci?

2024-11-24 05:40 UTC, RohittCodes commented
yeah all the deps are up to date, and i don't think there is any timeout issue for `bun tests`, but the playwright-test has timeout issues on `preview-page`. @seveibar

2024-11-24 06:38 UTC, seveibar commented
Hmm maybe configure for longer timeout in the config/workflow?

2024-11-24 07:53 UTC, RohittCodes commented
@seveibar nah this too doesn't work.

2024-11-24 19:56 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +    }
don't have redundant logic for the default manual edits json, the `useEffect` already handles it

2024-11-24 19:56 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +        setManualEditsFileContent(snippet.manual_edits_json)
this should be returned as JSON from the api, if it's not we should make it so it does

2024-11-24 19:57 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +  }, [manualEditsFileContent])
this try catch pattern is not good, let's revert that

2024-11-24 19:57 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +        setManualEditsFileContent(snippet.manual_edits_json)
if it's returned as a string, the name should be `manual_edits_json_content`

2024-11-24 19:58 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +      }
this is good

2024-11-24 19:59 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +  }, [manualEditsFileContent])
actually this is ok, but this file is getting too big so create a utility function in the utils directory `parseJsonOrDefault(manualEditsFileContent, {})`

2024-11-24 20:02 UTC, seveibar requested changes
this is a pretty good implementation, but i'm very critical of this file getting too big and difficult to understand so I'm going to insist on some small details, mostly...

- Only handle setting manual edits json in a single point
- We can remove any code that uses the template, we don't need the template especially if we set it to the empty project when it fails to parse
- The failure to parse really shouldn't go to an empty object- that basically means that we're overriding the user data when we fail to parse and erasing the previous content- this is very bad and buggy behavior. We should instead set the manualEditsFileContent to the string, then allow the user to edit it to correct it, not erase it

2024-11-27 21:36 UTC, seveibar commented on playwright-tests/manual-edits.spec.ts
> +})
this is great except i'm not sure why the screenshot is incorrect, the component hasn't moved

2024-11-27 21:42 UTC, seveibar requested changes
really really close, most of the issue is with the unconventional function. After that, we just need to consider why the screenshot is wrong- is the functionality broken? If not, why is the screenshot incorrect?

2024-11-27 21:42 UTC, seveibar commented on src/lib/utils/parseJson.ts
> +    return { value: jsonString }
this is a bad pattern,

1) we never use the meaningless variable name `value` unless there is some industry-specific reason we have to

2) the function name makes what this does unclear

3) if something fails to parse, there are only two appropriate conventions: return null OR return a "go-style" error e.g. `return { error } | { error: null, json }`

4) the filename doesn't match the function name

2024-11-27 21:42 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +  const [manualEditsFileContent, setManualEditsFileContent] = useState("{}")
you're not consistent with the default value- make it the empty string as it is in other places

2024-11-27 21:42 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +      "./manual-edits.json": parseJsonOrString(manualEditsFileContent),
```suggestion
      "./manual-edits.json": parseJsonOrNull(manualEditsFileContent) ?? "",
```

2024-12-06 11:56 UTC, seveibar requested changes
We’re very close now

2024-12-06 11:56 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +    parseJsonOrNull(""),
Just say null

2024-12-06 11:56 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +        parseJsonOrNull(manualEditsFileContent)
praseJsonOrNull cant throw, remove this try catch

2024-12-07 01:46 UTC, seveibar approved these changes
Cc @imrishabh18 we need to update the prod api to support the column rename

2024-12-09 07:38 UTC, seveibar commented
@RohittCodes I looked at the failing snapshots and they look like something is legit broken:

![image](https://github.com/user-attachments/assets/1810fbc7-7c8d-4b90-806d-28277c68fc1e)

2024-12-09 07:40 UTC, RohittCodes commented
yeah will look into this 👍

2024-12-09 07:52 UTC, seveibar commented
/tip $10

2024-12-09 08:32 UTC, RohittCodes commented
the issue was with the imports in view-snippet. fixed it! and it seems like there were changes on the editor page, will update the playwright tests for that.
![Screenshot 2024-12-09 135957](https://github.com/user-attachments/assets/a4860a2f-79e2-49ba-9c41-6951abb179b3)

https://github.com/user-attachments/assets/b0000806-214e-41d1-83c7-3bc78c1656e8

2024-12-09 09:59 UTC, seveibar commented
@RohittCodes nice work

2024-12-09 09:59 UTC, merged