feat: expand-preview
tscircuit/snippets pull request #285
Opened 2024-11-25 14:48 UTC by RohittCodes

fixes #146 
![image](https://github.com/user-attachments/assets/4e0a0921-8046-4f33-80a4-12ee5747b161)

2024-11-27 18:14 UTC, imrishabh18 reviewed
LGTM!!

2024-11-27 21:33 UTC, seveibar commented on src/components/PreviewContent.tsx
> +                onClick={onFullScreen}
```suggestion
                onClick={onToggleFullScreen}
```

2024-11-27 21:34 UTC, seveibar requested changes
minor name change, then good to go

2024-11-28 01:28 UTC, seveibar approved these changes
nice

2024-11-28 01:28 UTC, merged