fix: rename timeout
tscircuit/snippets pull request #297
Opened 2024-11-28 01:16 UTC by RohittCodes

added a timeout and introduced a finally block

fixes: #295
/claim #295

2024-11-28 01:17 UTC, seveibar requested changes
this is fine, but can you switch this to use a react-query mutation instead? This type of logic should always use react-query

2024-11-28 01:45 UTC, RohittCodes commented
this an api endpoint that failed. no changes made from my end.

2024-11-28 01:47 UTC, seveibar commented
@RohittCodes use this

![image](https://github.com/user-attachments/assets/0706e0fe-862f-46f8-8d99-56ee07645b50)


@Abse2001 can you confirm this fixes the underlying issue? I'm not super familiar w/ the problem

@RohittCodes nice refactor

2024-11-28 04:36 UTC, Abse2001 commented
@seveibar I will need few hours before I can test it Im going to collage.

2024-11-28 04:38 UTC, Abse2001 commented
It happens when you try to use a name that is not acceptable, eg (using spaces), after the fail message the dialog screen just stuck on renaming state, you can't change the name until you close it and open a new dialog.

2024-12-01 19:44 UTC, Abse2001 commented
@RohittCodes sorry for the delay I tested it and it looks fixed.
just fix the bun test and you are all good.

2024-12-02 00:18 UTC, RohittCodes commented
@Abse2001 I actually don't know why the bun tests failed, I've not even tried changing anything in the api.

It's completely a frontend change.

2024-12-02 02:54 UTC, seveibar commented
I think the bun tests are kind of flaky, just gotta rerun them (if that is the cause)

2024-12-02 02:55 UTC, seveibar commented on src/components/dialogs/rename-snippet-dialog.tsx
> +    renameSnippetMutation.mutate()
Just use an inline function here, these “handle” functions rarely increase readability especially when they are just proxying a mutation

2024-12-02 06:11 UTC, seveibar approved these changes

2024-12-04 09:55 UTC, merged