refactor: search-links
tscircuit/snippets pull request #307
Opened 2024-11-30 05:56 UTC by RohittCodes

fixes #104

2024-11-30 05:59 UTC, seveibar requested changes
Is there a way to do this that uses the Link element

2024-11-30 05:59 UTC, seveibar commented on src/components/SearchComponent.tsx
> +  const shouldOpenInNewTab = () => {
This should be a variable not a function

2024-11-30 06:00 UTC, seveibar commented
A lot of the code is repeated in the ternary, why not just have the prop to Link change? Does it not work?

2024-11-30 06:21 UTC, RohittCodes commented
Link component from the wouter library doesn't handle `targets` natively, it loads the content in the same tab as part of SPA navigation. I’ve tried using anchor tags too, but I noticed that they trigger a full-page reload unless handled by the router so came up with this @seveibar.

2024-11-30 06:24 UTC, seveibar commented
@RohittCodes ok, if you fix the var/func issue then ill approve

2024-11-30 12:16 UTC, seveibar requested changes

2024-11-30 12:16 UTC, seveibar commented on src/components/SearchComponent.tsx
> +  const openInNewTab = location === "/editor" || location === "/ai"
don't use verbs for variable names, verbs are for function names. `shouldOpenInNewTab` is a var name

```suggestion
  const shouldOpenInNewTab = location === "/editor" || location === "/ai"
```

2024-12-01 23:25 UTC, seveibar requested changes
can you add a test for this, sorry it's taking so long but i'm skeptical of the location only having the classname and not query parameters etc.

2024-12-02 06:21 UTC, RohittCodes commented
@seveibar should i work on the existing search specs for the tests or should i create a new file?

2024-12-02 06:28 UTC, seveibar commented
I generally prefer new files!

2024-12-03 07:40 UTC, seveibar approved these changes

2024-12-03 07:40 UTC, seveibar commented on playwright-tests/search-links.spec.ts
> +  console.log(popupUrl)
```suggestion
```

2024-12-04 14:04 UTC, merged