refactor: error-msg
tscircuit/snippets pull request #362
Opened 2024-12-08 06:44 UTC by RohittCodes

![Screenshot 2024-12-08 115921](https://github.com/user-attachments/assets/769534cb-73af-44b5-a46c-91a2e3fc7f8e)

the issue is most likely to be in the core package. where there is a type mismatch or some unexpected property access for the dimension x in the `_getPcbCircuitJsonBounds()`, `doInitialPcbPrimitiveRender()` methods. cc: @imrishabh18 

/claim #342 
fixes: #342

2024-12-08 09:03 UTC, imrishabh18 approved these changes

2024-12-08 23:21 UTC, seveibar requested changes
This error isnt more helpful, give a readable string that tells the user how to fix the bug (something about the shape or something)

reproduce rishabhs example in a test and test for the new error message

2024-12-09 01:05 UTC, RohittCodes commented
yeah but the error seems to be in the package but not the code. and it's fixed now. @seveibar

2024-12-09 01:23 UTC, seveibar commented
We can transfer the issue or when you update the core dep you can claim on that issue

2024-12-09 06:03 UTC, imrishabh18 commented
Yeah, I have fixed this in core. After that it didn't made sense to change the message here. Closing the issue

2024-12-09 06:04 UTC, closed without merging