will persist snippet data across the login session
tscircuit/snippets pull request #400
Opened 2024-12-19 14:23 UTC by Niharika0104

Fixes - #399

2024-12-19 14:47 UTC, imrishabh18 requested changes

2024-12-19 14:47 UTC, imrishabh18 commented on src/hooks/use-global-store.ts
> +  snippetType: "board" | "package" | "model" | "footprint" | string | undefined
The snippet type shouldn't be `undefined` or `string`, when we are using the const names. It defeats the point of it

2024-12-19 14:47 UTC, imrishabh18 commented on src/hooks/use-run-tsx/index.tsx
> +  type?: "board" | "footprint" | "package" | "model" | string
Here as well, we shouldn't be using `string`

2024-12-19 14:50 UTC, Niharika0104 commented
@imrishabh18 Okay sure.So we should split tests across multiple files ?

2024-12-21 09:34 UTC, Niharika0104 commented
@imrishabh18 i'm unable to test these changes locally coz locally we are using fakeApi and not the redirecting the user to the github oauth page
![image](https://github.com/user-attachments/assets/e73c353f-de57-426e-825a-e459de214c9b)
the user will click on login to save button and when in prod env it will redirect user to the github oauth page and from there to the authorize page and if the authorize page sees that guest snippet variable exists in the local storage it will redirected to the editor page and I will extract the previous edited info from guest snippet and set it . If that's good then i will start writing a test for this

2024-12-21 12:44 UTC, imrishabh18 commented
@Niharika0104 Yeah, correct. I think we can merge this without test. What do you think @seveibar?

On the UI, you have converted the `Not logged in, can't save` tag beside the save button to `Login to save` as a button. From the user point of view, that button appears to be a tag, which is pointing me to Login on the header and not click on the tag itself.

2024-12-21 13:31 UTC, Niharika0104 commented
@imrishabh18 yeah when we click on login to save it will redirect to GitHub oauth page and on entering their credentials it will redirect them to editor page and the code editor and manual edits  json file will be populated with the info we saved in guest snippet variable present in the local storage
Hope this makes sense!!

2024-12-21 18:00 UTC, seveibar commented on src/components/CodeAndPreview.tsx
> +    } else if (!isLoggedIn && guestSnippet) {
i think this breaks the loading of templates?

2024-12-21 18:11 UTC, seveibar commented
@Niharika0104 I think this should be still testable in playwright if you create a fake-api login route, the url is something like:

- `internal/oauth/github/authorize?next=${nextUrl}/authorize`

Overall i like the implementation, except i think most users will click "login" in the header rather than the badge.

It's a bit of work but if you're down i would recommend pausing this PR, then implementing a PR that just allows logging in inside playwright tests (issue: https://github.com/tscircuit/snippets/issues/409)

Overall it's a good idea to store the guest session inside the global store. But I'm cautious about the loading process- we might want to have a specialized hook or something that runs the appropriate state machine because the `<CodeAndPreview />` file scares me. But I'm not quite sure how to do this refactor yet-

2024-12-22 02:19 UTC, seveibar commented
@Niharika0104 i was looking at the logic in a bit more detail, it seems like the playwright test should be able to login due to this login logic:

![image](https://github.com/user-attachments/assets/52fb7f4d-b0cb-4e28-9d18-358644abf305)

2024-12-22 04:51 UTC, Niharika0104 commented
Yeah the tests are fine now but when we click on login /sign up on the header it takes us to the home page(/) but when we click on the login to save button it will take us to GitHub oauth and then to the editor page.
I tried testing it in the vercel preview site but GitHub oauth is not working there @seveibar

2024-12-22 04:58 UTC, seveibar commented
Yea i cant enable auth in preview

We should use the same code/logic for both logins, there's a sign in hook that should handle it iirc

2024-12-22 05:01 UTC, Niharika0104 commented
Yeah Im aware of that hook let me try again 
Thanks @seveibar

2025-01-18 00:18 UTC, closed without merging