I implemented a Download circuitJson button and the corresponding download function.
tscircuit/snippets pull request #49
Opened 2024-10-10 16:21 UTC by Abse2001

commit #17

2024-10-10 16:33 UTC, seveibar requested changes
see comment, useRunTsx is pretty expensive, i would also recommend the `file-saver` module from @DhairyaMajmudar PR, you could also implement a different download format to avoid conflicts

2024-10-10 16:33 UTC, seveibar commented on src/components/EditorNav.tsx
> +  const { circuitJson } = useRunTsx(code, snippet?.snippet_type)
can you avoid using `useRunTsx`? It's a very expensive hook and the circuitJson should be computed elsewhere

2024-10-11 18:00 UTC, seveibar commented on src/components/EditorNav.tsx
> +          fileName={snippet.unscoped_name}
important concept: "variable transarency" means you keep the same variable name as it is passed around. Don't rename variables if you don't have to. When I read this code, i was surprised that fileName was the same as the unscoped name, i expected it to have an extension. Naming is hard, renaming makes you have to do it more often

```suggestion
          snippetUnscopedName={snippet.unscoped_name}
```

2024-10-11 18:01 UTC, seveibar commented on src/lib/download-fns/download-circuit-json-fn.ts
> +  }
anti-pattern: useless try catch (it doesn't do anything here)

```suggestion
  const circuitJson = JSON.stringify(content, null, 2)
  const blob = new Blob([circuitJson], { type: "application/json" })
  saveAs(blob, fileName)
```

2024-10-11 18:01 UTC, seveibar commented on src/pages/view-snippet.tsx
> -              <DownloadButtonAndMenu />
why remove from this page? can't we give it the props?

2024-10-11 18:02 UTC, seveibar requested changes
see comments

2024-10-11 18:03 UTC, DhairyaMajmudar commented
It seems like I've already implemented this feature here https://github.com/tscircuit/snippets/pull/26

2024-10-11 18:08 UTC, seveibar commented
@DhairyaMajmudar for small features like this it's just whoever gets it right first, I don't do assignment unless it's a big feature. In open-source a project can be completely stalled when people don't fix PRs quickly etc. so we won't operate where people can work on things first

The best way to get issues assigned exclusively to you is to get familiar with the codebase and work on hard issues that people don't generally want, or find bugs and create your own issues.

2024-10-11 20:17 UTC, seveibar approved these changes

2024-10-11 20:18 UTC, merged