fixed:quickstart page responsiveness
tscircuit/snippets pull request #95
Opened 2024-10-19 07:50 UTC by theajmalrazaq

just fixed the quickstart page responsivess it is subpart of issue #25:mobile view is broken
![Screenshot_select-area_20241019124711](https://github.com/user-attachments/assets/ba4a952f-abc0-4a2c-9c02-11e2a2420767)
![Screenshot_select-area_20241019124722](https://github.com/user-attachments/assets/14f95374-8fce-4308-88e8-2049ef2b26e9)

2024-10-19 16:17 UTC, seveibar requested changes
Change the number of grid cols not the display style (this is a good use case for grid, switching to flex isnt as good)

2024-10-19 16:49 UTC, theajmalrazaq commented
@seveibar  Done!!

2024-10-19 17:23 UTC, seveibar commented
So it looks like youve changed the design on lg screens.

im mobile today so its harder to check work. Can you introduce a playwright snapshot test (see playwright-tests directory) for xs, md and lg sizes. This will also benefit the project because others will need to show their snapshot for future modifications

2024-10-19 19:34 UTC, theajmalrazaq commented
@seveibar, this is how it looks on both devices. On large devices, there will be 3 columns, and on mobile, there will be 1 column. Furthermore, I am working on Playwright tests for 3 screen sizes: large, medium, and extra small, and I’m fixing the AI page UI. I will create their PR tomorrow. Also, I will work on setting the screen to ensure it is fixed across mobile. With all these updates, issue #25 will be closed. For now, please merge this.

![Screenshot_select-area_20241020002600](https://github.com/user-attachments/assets/674b5e35-9513-471d-b507-a06c70bcf26d)
![Screenshot_select-area_20241020002546](https://github.com/user-attachments/assets/eed22231-ce41-417a-9512-f5b64b38cd2a)

2024-10-21 01:11 UTC, seveibar commented on src/pages/quickstart.tsx
> +          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
```suggestion
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4">
```

2024-10-21 01:11 UTC, seveibar commented on src/pages/quickstart.tsx
> +          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
```suggestion
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4">
```

2024-10-21 01:12 UTC, seveibar commented on src/pages/quickstart.tsx
> +            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
```suggestion
            <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4">
```

2024-10-21 01:12 UTC, seveibar reviewed
See comments, then good to go

2024-10-21 01:14 UTC, theajmalrazaq commented
@seveibar doing it right away.

2024-10-21 01:43 UTC, theajmalrazaq commented
@seveibar Done with this!

2024-10-21 01:54 UTC, seveibar approved these changes

2024-10-21 02:47 UTC, merged